In [1]:
import numpy as np
import cv2
import os
from os import makedirs,listdir
from random import random,shuffle
from shutil import copyfile
import matplotlib.pyplot as plt
import pickle

In [2]:
#Create directories
image_dataset='Images_Dataset/'
labeldirs=['Sarees/','Trousers/','Jeans/']
for labeldir in labeldirs:
    newdir=image_dataset+labeldir
    makedirs(newdir, exist_ok=True)

In [3]:

directory=r'C:\Users\user\OneDrive\Pictures\images'
dataset='Images_Dataset/'
for file in listdir(directory):
    src=directory + '/' + file
    if 'Sarees' in file:
        dst=dataset +  'Sarees/' + file
        copyfile(src,dst)
    elif 'Jeans' in file:
        dst=dataset +  'Jeans/' + file
        copyfile(src,dst)
    elif 'Trousers' in file:
        dst=dataset +  'Trousers/' + file
        copyfile(src,dst)


In [4]:
Directory=r'C:\Users\user\Documents\Python\Images_Dataset'
categories=['Jeans','Sarees','Trousers']

In [5]:
data=[]
for category in categories:
    folder=os.path.join(Directory,category)
    label=categories.index(category)
    for img in os.listdir(folder):
        img_path=os.path.join(folder, img)
        img_arr=cv2.imread(img_path)
        img_arr=cv2.resize(img_arr,(224,224))
        data.append([img_arr,label])

In [6]:
len(data)

600

In [7]:
#Seperating features and labels
x=[]
y=[]
for features, labels in data:
    x.append(features)
    y.append(labels)

In [8]:
x=np.array(x)
y=np.array(y)

In [9]:
x

array([[[[253, 254, 255],
         [174, 177, 183],
         [ 94, 101, 113],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[252, 254, 255],
         [233, 237, 240],
         [182, 190, 198],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[251, 254, 255],
         [250, 253, 255],
         [236, 241, 246],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [251, 250, 250],
         [253, 253, 253],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
        

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [11]:
#Normalizing the pixels to be values between 0 and 1
X=x/255

In [12]:
X.shape

(600, 224, 224, 3)

In [13]:
y.shape

(600,)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [15]:
x_train.shape

(480, 224, 224, 3)

In [16]:
y_train.shape

(480,)

In [17]:
x_test.shape

(120, 224, 224, 3)

In [18]:
y_test.shape

(120,)

In [19]:
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Flatten,Dense

In [20]:
model=Sequential()
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D((2,2)))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128,input_shape=X.shape[1:],activation='relu'))
model.add(Dense(3,activation='softmax'))

In [21]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [22]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
15/15 [==============================] - 140s 7s/step - loss: 2.5453 - accuracy: 0.5396
Epoch 2/5
15/15 [==============================] - 68s 5s/step - loss: 0.3499 - accuracy: 0.8729
Epoch 3/5
15/15 [==============================] - 175s 12s/step - loss: 0.2067 - accuracy: 0.9167
Epoch 4/5
15/15 [==============================] - 390s 25s/step - loss: 0.1300 - accuracy: 0.9604
Epoch 5/5
15/15 [==============================] - 52s 3s/step - loss: 0.0768 - accuracy: 0.9646


In [23]:
model.evaluate(x_test,y_test)

4/4 [==============================] - 83s 736ms/step - loss: 0.3956 - accuracy: 0.8500


[0.395608514547348, 0.8500000238418579]

In [24]:
y_test

array([0, 1, 0, 1, 1, 0, 0, 0, 1, 2, 1, 2, 0, 1, 1, 1, 2, 0, 2, 1, 1, 2,
       2, 0, 0, 2, 0, 2, 2, 0, 1, 2, 2, 0, 1, 1, 1, 0, 2, 0, 0, 0, 0, 2,
       2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 0, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 2, 2, 2, 0, 1, 2, 1, 0, 0, 0, 1, 2, 2, 1, 1, 1, 2,
       2, 2, 0, 0, 0, 2, 1, 0, 1, 1, 2, 2, 0, 1, 2, 1, 1, 2, 2, 0, 1, 1,
       1, 2, 2, 1, 0, 1, 1, 0, 0, 1])

In [25]:
y_pred=model.predict(x_test)
y_pred[:5]

array([[9.9576074e-01, 1.4640586e-04, 4.0928749e-03],
       [1.5741150e-23, 1.0000000e+00, 1.0829214e-15],
       [9.9799228e-01, 6.7204020e-08, 2.0076430e-03],
       [1.8866653e-16, 1.0000000e+00, 2.7952785e-14],
       [2.3290731e-05, 9.9993575e-01, 4.0969819e-05]], dtype=float32)

In [26]:
y_classes=[np.argmax(element) for element in y_pred]
y_classes[:5]

[0, 1, 0, 1, 1]

In [27]:
from sklearn.metrics import classification_report,accuracy_score

In [28]:
print('Accuracy score :',accuracy_score(y_test,y_classes))
print('Classification Report :\n',classification_report(y_test,y_classes))

Accuracy score : 0.85
Classification Report :
               precision    recall  f1-score   support

           0       0.74      0.89      0.81        38
           1       0.96      0.98      0.97        46
           2       0.85      0.64      0.73        36

    accuracy                           0.85       120
   macro avg       0.85      0.84      0.84       120
weighted avg       0.86      0.85      0.85       120

